# Generated by Django 5.2.12 on 2026-03-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_floorplan', '0012_alter_floorplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='canvas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
