name: NetBox plugin manifest modified

on:
  push:
    branches: [ master ]
    paths:
      - netbox-plugin.yaml

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  manifest-modified:
    uses: netboxlabs/public-workflows/.github/workflows/reusable-plugin-manifest-modified.yml@release
